name: SEO

on:
  schedule:
    - cron: "0 23 * * *" # 每天国际标准时间23点（北京时间+8即早上7点）运行
env:
  TZ: Asia/Shanghai

jobs:
  SEO: # 一项叫做SEO的任务
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行

    steps:
      - name: Checkout codes # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@master # 脚本来自 https://github.com/actions/checkout
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 1

      - name: Setup Node # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "12.x"

      - name: Cache
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Install plugins
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: SEO
        run: |
          npx hexo d
